app = 'rollups-node'

region = 'ams'

[build]
  image = 'ghcr.io/sunodo/sunodo-node:pr-198'

[env]
  CARTESI_LOG_LEVEL = 'info'
  CARTESI_BLOCKCHAIN_ID = '11155111'
  CARTESI_SNAPSHOTS_DIR = '/var/lib/cartesi-rollups-node/snapshots'
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = '0xc70074BDD26d8cF983Ca6A5b89b8db52D5850051'
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS = '0xC7003566dD09Aa0fC0Ce201aC2769aFAe3BF0051'
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS = '0xc7006f70875BaDe89032001262A846D3Ee160051'
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS = '0xc700285Ab555eeB5201BC00CFD4b2CC8DED90051'

[http_service]
  internal_port = 8080
  force_https = true

[http_service.concurrency]
  type = 'requests'
  hard_limit = 250
  soft_limit = 200

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[metrics]]
  port = 9000
  path = '/metrics'