#
# Contracts
#

[contracts.SHOAL_ADMIN_ADDRESS]
go-type = "Address"
default = "0xD554153658E8D466428Fa48487f5aba18dF5E628"
description = """Address of the admin user"""
used-by = ["rollup"]

[contracts.SHOAL_ADMIN_ADDRESS_TEST]
go-type = "Address"
default = "0x976EA74026E726554dB657fA54763abd0C3a0aa9"
description = """Address of the admin user"""
used-by = ["rollup"]

[contracts.SHOAL_VERIFIER_ADDRESS]
go-type = "Address"
default = "0xc2D8eb4a934AEc7268E414a3Fa3D20E0572d714b"
description = """Address of the verifier user, who can verify the social accounts"""
used-by = ["rollup"]

[contracts.SHOAL_VERIFIER_ADDRESS_TEST]
go-type = "Address"
default = "0x0000000000000000000000000000000000000025"
description = """Address of the verifier user, who can verify the social accounts"""
used-by = ["rollup"]